server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
